# ^ Dockerfile для frontend (Next.js)

# Используем официальный легковесный образ Node.js
FROM node:18-alpine AS builder

# устан.раб.п.frontend
WORKDIR /frontend

# копир.все package*.json > устан.зависимостей
COPY package*.json ./

# устан.зависимости по package-lock.json
RUN npm ci

# копир.все ф.проекта в Контейнер
COPY . .

# сбор.приложения
RUN npm run build

# Этап > запуска приложения
FROM node:18-alpine AS runner

# устан.раб.п.frontend
WORKDIR /frontend

# копир.нужные зависимости
COPY --from=builder /frontend/.next ./.next
COPY --from=builder /frontend/public ./public
COPY --from=builder /frontend/package.json ./package.json
COPY --from=builder /frontend/package-lock.json ./package-lock.json

# устан.production зависимости по package-lock.json
RUN npm ci --only=production

# устан.перем.окруж.production
ENV NODE_ENV=production

# указ.порт приложением
EXPOSE 3000

# запуск приложения
CMD ["npm", "run", "start"]