export enum FileType {
  ALL = 'all',
  IMAGE = 'image',
  ALBUM = 'album',
  PICTURE = 'picture',
  AVATAR = 'avatar',
  PHOTO = 'photo',
  PERSONAL = 'personal',
  AUDIO = 'audio',
  TRACK = 'track',
  BOOK = 'books',
  FILE = 'files',
  PROSE = 'prose',
  CODE = 'code',
  SCHEME = 'scheme',
  BLUEPRINT = 'blueprint',
  TRASH = 'trash',
  OTHER = 'other',
}

export const fileTypePaths: Record<FileType, string> = {
  [FileType.ALL]: 'all',
  [FileType.IMAGE]: 'images',
  [FileType.PICTURE]: 'images/picture',
  [FileType.AVATAR]: 'users/avatar',
  [FileType.ALBUM]: 'images/album',
  [FileType.PHOTO]: 'users/photo',
  [FileType.PERSONAL]: 'users/personal',
  [FileType.AUDIO]: 'audios',
  [FileType.TRACK]: 'audios/track',
  [FileType.BOOK]: 'books/book',
  [FileType.FILE]: 'books/file',
  [FileType.PROSE]: 'books/prose',
  [FileType.CODE]: 'prog/code',
  [FileType.SCHEME]: 'prog/scheme',
  [FileType.BLUEPRINT]: 'prog/blueprint',
  [FileType.TRASH]: 'other',
  [FileType.OTHER]: 'other', // Запасной вариант для других типов
};
