import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          Layout--*0*1*2*3*4*5*6*7*8*9*10*11*12*13*14*15*16*17*18*19*20*--Layout
        </div>
        <Navbar />
        {children}
        <div>
          Layout-^^-*0*1*2*3*4*5*6*7*8*9*10*11*12*13*14*15*16*17*18*19*20*-^^-Layout
        </div>
      </body>
    </html>
  );
}
